# -*- coding: utf-8 -*-
"""quiz application

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMwgfA0VzBj8u7xv88brWrCjCz0PwLBC
"""



# prompt: quiz application

def quiz():
  score = 0
  questions = [
      {
          "question": "What is the capital of France?",
          "options": ["Berlin", "Paris", "Madrid", "Rome"],
          "answer": "Paris"
      },
      {
          "question": "What is the highest mountain in the world?",
          "options": ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"],
          "answer": "Mount Everest"
      }
  ]

  for question in questions:
      print(question["question"])
      for i, option in enumerate(question["options"]):
          print(f"{i+1}. {option}")

      user_answer = input("Enter your answer (1-4): ")
      if question["options"][int(user_answer)-1] == question["answer"]:
          score += 1
          print("Correct!\n")
      else:
          print(f"Incorrect. The answer is {question['answer']}\n")

  print(f"You got {score} out of {len(questions)} questions correct.")

if __name__ == "__main__":
  quiz()